[deploy_config]
salt = "zkWormholes ERC20"
chains = ["op_chain_a","op_chain_b"]

[token]
owner_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
name = "zkWormholesERC20"
symbol = "zkERC20"
decimals = 18
